services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    container_name: django
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./server/.env

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: ./Dockerfile.dev
  #   container_name: react
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   ports:
  #     - 5173:5173
  #   depends_on:
  #     - server

volumes:
  postgres_data:
